AllCops:
  TargetRubyVersion: 2.2
  DisabledByDefault: true
  Exclude:
    - "examples/instrumentation.rb"

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Layout:
  Enabled: true

Lint:
  Enabled: true

Naming:
  Enabled: true
  Exclude:
    - "lib/rack/attack/path_normalizer.rb"

Performance:
  Enabled: true

Security:
  Enabled: true

Lint:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

# TODO
# Remove cop disabling and fix offenses
Lint/HandleExceptions:
  Enabled: false
