language: ruby
cache: bundler

rvm:
  - 2.6.0-preview1
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - jruby-9.1.16.0

before_install:
  # For jruby we need to stick with rubygems 2.7.4 until
  # https://github.com/rubygems/rubygems/issues/2188
  # is fixed and released.
  #
  # Without this workaround, for jruby builds, rubygems
  # activates jruby stdlib minitest (v5.4.1) instead of the
  # bundled version (v5.11.3).
  - if [ "$TRAVIS_RUBY_VERSION" = "jruby-9.1.16.0" ]; then gem update --system 2.7.4; else gem update --system; fi
  - gem install bundler

gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/dalli2.gemfile

matrix:
  allow_failures:
    - gemfile: gemfiles/rails_5_2.gemfile
    - rvm: 2.6.0-preview1

  fast_finish: true

services:
  - redis
  - memcached
