language: ruby
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - jruby-9.1.14.0

before_install:
  - gem update --system
  - gem install bundler

gemfile:
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/dalli2.gemfile

services:
  - redis
  - memcached
